In [1]:
import numpy as np
import os,sys,inspect


currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir) 
from func.Select_Index import Select_Columns, Select_Rows, Select_Ind


In [2]:

n = 4      # размерность задачи

m = 5
n = 4
A = np.random.rand(m, n) * 10
S = [1, 3]
W = [0, 2]
print("A = \n {}".format(A))
print("=============\n")
print("S : {} \n\nW : {} \n\n A[:, S] = \n {} \n\n A[W, :] = \n {} \n\n A[W, S] = \n {} \n"\
      .format(S, W,  Select_Columns(A, S), Select_Rows(A, W), Select_Ind(A, W, S)))

A = 
 [[1.68370209 3.28981722 6.57638716 6.9743429 ]
 [4.0989749  1.82051714 8.2665402  1.41750682]
 [5.937801   3.85717582 7.98124289 9.54823749]
 [9.34935663 7.19476449 8.09212123 9.64438581]
 [0.89187135 4.42107522 6.75324034 1.10953657]]

S : [1, 3] 

W : [0, 2] 

 A[:, S] = 
 [[3.28981722 6.9743429 ]
 [1.82051714 1.41750682]
 [3.85717582 9.54823749]
 [7.19476449 9.64438581]
 [4.42107522 1.10953657]] 

 A[W, :] = 
 [[1.68370209 3.28981722 6.57638716 6.9743429 ]
 [5.937801   3.85717582 7.98124289 9.54823749]] 

 A[W, S] = 
 [[3.28981722 6.9743429 ]
 [3.85717582 9.54823749]] 

