In [1]:
import numpy as np
import math
import os,sys,inspect


currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir) 
from func.Bidiag_Rotations import house_bidiag

In [2]:
n = 6
m = 6
A = np.random.rand(m, n) * 10

#A = np.arange(1,13.0).reshape(4,3)
A_test = np.copy(A)
print(A)

U, B, Vt = house_bidiag(A, full=True)
print("B:\n", B)
print("U:\n", U)
print("Vt:\n", Vt)

print("should equal input:", np.allclose(U.dot(B).dot(Vt), A_test))


B = house_bidiag(A, full=False)
print("B:\n", B)


[[7.66361392 3.80769446 8.83887748 7.83340265 0.40986901 6.40789918]
 [9.56435432 3.34330719 7.05671118 7.14989351 8.59133437 6.78164814]
 [0.09550519 8.02280474 7.87862685 2.07160029 4.53321636 2.89400154]
 [1.9928244  6.46139565 9.17594915 8.91570569 7.69212511 1.67556806]
 [2.75334966 3.98648603 6.07021742 2.07441943 4.94359901 7.34075073]
 [0.70822178 6.92095033 5.87482405 4.49739925 6.31310742 5.98203454]]
B:
 [[12.73855701 24.49718328  0.          0.          0.          0.        ]
 [ 0.         20.39277383  7.67910617  0.          0.          0.        ]
 [ 0.          0.          3.12803646  1.86623215 -0.         -0.        ]
 [ 0.         -0.         -0.          4.94283833  2.9810259   0.        ]
 [ 0.          0.          0.         -0.          1.91129536  0.87475216]
 [ 0.         -0.         -0.         -0.          0.         -6.47153243]]
U:
 [[ 0.6016077  -0.08333953 -0.38811392 -0.67646995 -0.02494729  0.14918554]
 [ 0.75081929 -0.17339315  0.44065861  0.42025504  